#ifndef FA18_COMMAND_SELECTION_H
#define FA18_COMMAND_SELECTION_H
#include "memory.h"

/* Dispatch policy component of the complete C1AC28/C1AD74 owners.
 * Selecting an action is separate from executing its shared command tail.
 * This component alone is not a completed/registered original routine. */
enum CommandAction {
    COMMAND_PENDING_EMPTY, COMMAND_COUNTER_WAIT, COMMAND_INVALID_WORD,
    COMMAND_QUEUE_ONLY, COMMAND_FINISH_EVENT, COMMAND_RESET_CONTEXT,
    COMMAND_SPACE, COMMAND_SPACE_RELEASE, COMMAND_EJECT, COMMAND_NEXT_TARGET,
    COMMAND_WEAPON_MODE, COMMAND_RADAR_RANGE, COMMAND_INFO_PAGE, COMMAND_HUD,
    COMMAND_GEAR, COMMAND_HOOK, COMMAND_FLARE, COMMAND_CHAFF, COMMAND_ECM,
    COMMAND_TARGET, COMMAND_MAP, COMMAND_SIGN_INPUT, COMMAND_CONTEXT_SPECIAL,
    COMMAND_CONTEXT_REQUEST, COMMAND_CONTEXT_REFRESH, COMMAND_CONTEXT_CALCULATION,
    COMMAND_Y_DOWN, COMMAND_Y_UP, COMMAND_Y_RELEASE,
    COMMAND_X_RIGHT, COMMAND_X_LEFT, COMMAND_X_RELEASE,
    COMMAND_TRIM_A, COMMAND_TRIM_B, COMMAND_TRIM_RELEASE,
    COMMAND_THROTTLE_UP, COMMAND_THROTTLE_DOWN, COMMAND_THROTTLE_RELEASE,
    COMMAND_THROTTLE_MODE, COMMAND_CONTEXT_VIEW_DECREMENT, COMMAND_CONTEXT_VIEW_INCREMENT,
    COMMAND_CONTEXT_VIEW_ALTERNATE, COMMAND_VIEW_ZERO, COMMAND_VIEW_ONE,
    COMMAND_VIEW_INCREMENT, COMMAND_VIEW_DECREMENT, COMMAND_VIEW_TWELVE,
    COMMAND_VIEW_THIRTEEN, COMMAND_VIEW_THREE, COMMAND_VIEW_NINE,
    COMMAND_VIEW_TOGGLE, COMMAND_VIEW_EIGHT, COMMAND_FIRE_REQUEST,
    COMMAND_ZOOM_OUT, COMMAND_ZOOM_IN, COMMAND_LOW_INDEX,
    COMMAND_FUNCTION_LEVEL, COMMAND_INDEXED
};
enum CommandSelectionPhase {
    COMMAND_READ_EVENT, COMMAND_TEST_COUNTER, COMMAND_INCREMENT_COUNTER,
    COMMAND_CLEAR_RELEASE, COMMAND_READ_ORIGIN, COMMAND_READ_MODIFIER,
    COMMAND_READ_DETAIL, COMMAND_COMPARE_DETAIL, COMMAND_READ_RECORDER,
    COMMAND_COMPARE_RECORDER, COMMAND_COMPARE_MODE, COMMAND_COMPARE_GATE,
    COMMAND_TEST_BYTE, COMMAND_COMPARE_KEY, COMMAND_READ_BLOCK,
    COMMAND_SET_INDEX, COMMAND_SET_LATCH, COMMAND_CLEAR_CONTEXT,
    COMMAND_READ_WORD_A, COMMAND_MASK_WORD_A, COMMAND_PENDING_BEGIN,
    COMMAND_SELECT_WORD_B, COMMAND_TEST_WORD, COMMAND_CLEAR_WORD_BIT,
    COMMAND_CLEAR_LATCH
};
typedef struct {
    enum CommandAction action;
    uint32_t raw_event;
    uint8_t origin_mode, modifier, detail_state;
    int16_t index; /* valid for COMMAND_INDEXED only */
} CommandRequest;
typedef struct {
    void (*observe)(void *context, enum CommandSelectionPhase phase,
                    uint32_t value, uint32_t limit);
    void *context;
} CommandSelectionHooks;
CommandRequest select_keyboard_command(uint32_t raw_event,
                                       const CommandSelectionHooks *hooks);
CommandRequest select_pending_command(const CommandSelectionHooks *hooks);
#endif
