#ifndef FA18_COMMAND_TYPES_H
#define FA18_COMMAND_TYPES_H

#include <stdint.h>

/* Game command values shared by the native input pipeline and reference
 * adapters. These types have no CPU, guest memory or machine dependency. */
enum CommandAction {
    COMMAND_PENDING_EMPTY, COMMAND_COUNTER_WAIT, COMMAND_INVALID_WORD,
    COMMAND_QUEUE_ONLY, COMMAND_FINISH_EVENT, COMMAND_RESET_CONTEXT,
    COMMAND_SPACE, COMMAND_SPACE_RELEASE, COMMAND_EJECT, COMMAND_NEXT_TARGET,
    COMMAND_WEAPON_MODE, COMMAND_RADAR_RANGE, COMMAND_INFO_PAGE, COMMAND_HUD,
    COMMAND_GEAR, COMMAND_HOOK, COMMAND_FLARE, COMMAND_CHAFF, COMMAND_ECM,
    COMMAND_TARGET, COMMAND_MAP, COMMAND_SIGN_INPUT, COMMAND_CONTEXT_SPECIAL,
    COMMAND_CONTEXT_REQUEST, COMMAND_CONTEXT_REFRESH, COMMAND_CONTEXT_CALCULATION,
    COMMAND_Y_DOWN, COMMAND_Y_UP, COMMAND_Y_RELEASE,
    COMMAND_X_RIGHT, COMMAND_X_LEFT, COMMAND_X_RELEASE,
    COMMAND_TRIM_A, COMMAND_TRIM_B, COMMAND_TRIM_RELEASE,
    COMMAND_THROTTLE_UP, COMMAND_THROTTLE_DOWN, COMMAND_THROTTLE_RELEASE,
    COMMAND_THROTTLE_MODE, COMMAND_CONTEXT_VIEW_DECREMENT, COMMAND_CONTEXT_VIEW_INCREMENT,
    COMMAND_CONTEXT_VIEW_ALTERNATE, COMMAND_VIEW_ZERO, COMMAND_VIEW_ONE,
    COMMAND_VIEW_INCREMENT, COMMAND_VIEW_DECREMENT, COMMAND_VIEW_TWELVE,
    COMMAND_VIEW_THIRTEEN, COMMAND_VIEW_THREE, COMMAND_VIEW_NINE,
    COMMAND_VIEW_TOGGLE, COMMAND_VIEW_EIGHT, COMMAND_FIRE_REQUEST,
    COMMAND_ZOOM_OUT, COMMAND_ZOOM_IN, COMMAND_LOW_INDEX,
    COMMAND_FUNCTION_LEVEL, COMMAND_INDEXED
};
typedef struct {
    enum CommandAction action;
    uint32_t raw_event;
    uint8_t origin_mode, modifier, detail_state;
    int16_t index; /* valid for COMMAND_INDEXED only */
} CommandRequest;
#endif
