#ifndef FA18_HUD_HISTORY_STREAM_H
#define FA18_HUD_HISTORY_STREAM_H
#include "memory.h"
enum HudHistoryStreamField { HHS_VALUE,HHS_BASE,HHS_CONTROL,HHS_SECONDARY,HHS_SOURCE,HHS_STRIDE,HHS_SIZE,HHS_OFFSET,
    HHS_REGISTERS,HHS_TABLE,HHS_STREAM,HHS_DESCRIPTOR,HHS_SCREEN,HHS_MODULO,HHS_FRAME,HHS_STACK };
typedef struct {
    uint32_t value,base,control,secondary,source,stride,size,offset;
    gaddr registers,table,stream,descriptor,screen,modulo,frame,stack;
    int less;
} HudHistoryStreamState;
enum HudHistoryStreamChild { HHS_HISTORY_MAGNITUDE,HHS_HISTORY_TRANSFORM,HHS_HISTORY_QUARTER,HHS_HISTORY_HALF,HHS_HISTORY_THREE_QUARTER,HHS_HISTORY_POINT,HHS_ALTITUDE_PACK,HHS_ALTITUDE_DIGITS,HHS_ALTITUDE_LABEL,HHS_ALTITUDE_ANALOG_PACK,HHS_ALTITUDE_ROUND_PACK,HHS_ALTITUDE_UNPACK,HHS_ALTITUDE_PIXEL,HHS_ALTITUDE_TICK,HHS_ALTITUDE_DOWN_PIXEL,HHS_ALTITUDE_DOWN_TICK,HHS_ALTITUDE_UP_PIXEL,HHS_ALTITUDE_UP_TICK,HHS_ALTITUDE_BASE,HHS_ALTITUDE_SCALE,HHS_SPEED_PACK,HHS_SPEED_DIGITS,HHS_SPEED_LABEL,HHS_SPEED_ANALOG_PACK,HHS_SPEED_ROUND_PACK,HHS_SPEED_UNPACK,HHS_SPEED_TICK,HHS_SPEED_DOWN_TICK,HHS_SPEED_UP_TICK,HHS_SPEED_BASE,HHS_SPEED_SCALE,HHS_SPEED_LEFT_FIRST,HHS_SPEED_POINT_FIRST,HHS_SPEED_RIGHT_FIRST,HHS_SPEED_LEFT_SECOND,HHS_CENTRE_POINT,HHS_CENTRE_RIGHT,HHS_CENTRE_SECOND,HHS_HEADING_PACK,HHS_HEADING_ROUND_PACK,HHS_HEADING_UNPACK,HHS_HEADING_TICK,HHS_HEADING_RIGHT_TICK,HHS_HEADING_LEFT_TICK,HHS_HEADING_END,HHS_STREAM_POINT,HHS_STREAM_FIXED_POINT,HHS_STREAM_CIRCLE };
enum HudHistoryStreamPhase {
    HHS_WORD,HHS_BYTE,HHS_LONG,HHS_POINTER,HHS_ADD_WORD,HHS_SUB_WORD,HHS_ADD_LONG,HHS_SUB_LONG,HHS_NEG_WORD,
    HHS_SWAP,HHS_EXT_WORD,HHS_EXT_LONG,HHS_ASL_WORD,HHS_LSL_WORD,HHS_ASR_WORD,HHS_ASR_BYTE,HHS_LSR_LONG,HHS_ROR_WORD,
    HHS_AND_WORD,HHS_AND_BYTE,HHS_OR_WORD,HHS_COMPARE_WORD,HHS_COMPARE_BYTE,HHS_TEST_WORD,HHS_TEST_BYTE,
    HHS_BIT_TEST,HHS_BIT_CLEAR,HHS_STORE_BYTE,HHS_STORE_WORD,HHS_STORE_LONG,HHS_MEMORY_SUB_BYTE,
    HHS_DECREMENT,HHS_PUSH_LONG,HHS_POP_LONG,HHS_SAVE_WORDS,HHS_RESTORE_WORDS,HHS_ASR_LONG,HHS_LSR_BYTE,HHS_DIVU,HHS_DIVS,HHS_AND_LONG,HHS_COMPARE_LONG,HHS_MEMORY_LOGIC_LONG,HHS_SAVE_LONGS,HHS_RESTORE_LONGS,HHS_PUSH_WORD,HHS_POP_WORD,HHS_RAW_LONG,HHS_MULS,HHS_MULU,HHS_POP_POINTER,HHS_LOAD_WORDS_AT,HHS_STORE_WORDS_AT,HHS_LOAD_LONGS_AT,HHS_LINK_FRAME,HHS_UNLINK_FRAME,HHS_NEG_LONG,HHS_ADD_BYTE,HHS_MEMORY_ADD_BYTE,HHS_TEST_LONG,HHS_POP_MEMORY_LONG,HHS_DECIMAL_ADD,HHS_DECIMAL_SUB,HHS_SUB_BYTE,HHS_MEMORY_ADD_LONG
};
typedef struct {
    HudHistoryStreamState (*consume)(void *context,enum HudHistoryStreamChild child);
    void (*observe)(void *context,enum HudHistoryStreamPhase phase,enum HudHistoryStreamField field,uint32_t value,uint32_t operand);
    HudHistoryStreamState (*restored)(void *context);
    void *context;
} HudHistoryStreamHooks;
void hud_history_projection(HudHistoryStreamState w,const HudHistoryStreamHooks *h);
void hud_postflight_display(HudHistoryStreamState w,const HudHistoryStreamHooks *h);
void hud_stream_point(HudHistoryStreamState w,const HudHistoryStreamHooks *h,int fixed);
void hud_stream_circle(HudHistoryStreamState w,const HudHistoryStreamHooks *h);
#endif
