#ifndef FA18_MAIN_LOOP_TIMERS_H
#define FA18_MAIN_LOOP_TIMERS_H
#include "memory.h"
enum MainTimerChild { MT_SCALE_BOUNDS,MT_SAMPLE_BEGIN,MT_COUNT_FIRST,MT_COUNT_SECOND,MT_COUNT_THIRD,MT_SAMPLE_POLL };
enum MainTimerPhase {
    MT_BOUNDS_BEGIN,MT_BOUNDS_OFFSET,MT_BOUNDS_LOAD,MT_BOUNDS_SENTINEL,MT_BOUNDS_VECTOR,MT_BOUNDS_CORNERS,MT_BOUNDS_NEXT,
    MT_WORD_STORE,MT_LONG_STORE,MT_BYTE_STORE,MT_BYTE_TEST,MT_LONG_TEST,
    MT_ACCUMULATOR_LOAD,MT_SAMPLE_SUBTRACT,MT_SAMPLE_NEGATE,MT_SAMPLE_MULTIPLY,
    MT_FRACTION_LOAD,MT_FRACTION_SUBTRACT,MT_FRACTION_DIVIDE,MT_FRACTION_EXTEND,MT_SAMPLE_ADD,
    MT_TOTAL_ADD,MT_PARTIAL_ADD,MT_PARTIAL_COMPARE,MT_TOTAL_SUBTRACT,MT_TOTAL_COMPARE,MT_FLAGS_CLEAR,MT_FLAGS_SET,
    MT_SAMPLE_COMPARE,MT_DECREMENT_PRIMARY,MT_SECONDARY_CURSOR,MT_SECONDARY_CLEAR_BIT,MT_SECONDARY_DECREMENT,
    MT_COUNT_CURSOR,MT_LEVEL_LOAD,MT_LEVEL_ADD,MT_LEVEL_COMPARE,MT_LEVEL_MAXIMUM,MT_LEVEL_DECREMENT,
    MT_POLL_COMPARE,MT_DIVISOR_LOAD,MT_DIVISOR_MASK,MT_DIVISOR_INCREMENT,MT_POLL_DIVIDE,
    MT_THRESHOLD_BASE,MT_THRESHOLD_INDEX,MT_THRESHOLD_EXTEND,MT_THRESHOLD_SCALE,MT_THRESHOLD_COMPARE,
    MT_READOUT_LIMIT,MT_READOUT_SENTINEL,MT_READOUT_DIVIDEND,MT_READOUT_DIVIDE,MT_MINIMUM_COMPARE,MT_MAXIMUM_COMPARE
};
typedef struct { int16_t width,height; gaddr cursor,record; } MainTimerBounds;
typedef struct {
    MainTimerBounds (*consume)(void *context,enum MainTimerChild child);
    void (*observe)(void *context,enum MainTimerPhase phase,uint32_t value,uint32_t other);
    uint32_t (*divide_zero)(void *context);
    void *context;
} MainTimerHooks;
void prepare_setup_bounds(const MainTimerHooks *h);
void advance_main_loop_timers(const MainTimerHooks *h);
void sample_main_loop_readout(const MainTimerHooks *h);
#endif
