#ifndef FA18_MAIN_LOOP_FLIGHT_CONTROLS_H
#define FA18_MAIN_LOOP_FLIGHT_CONTROLS_H
#include "memory.h"
/* Named working values survive actual child calls. Full halves of these
 * source values matter when byte and word operations share the same value. */
typedef struct {
    uint32_t value,speed,turn,x,y,z,rate,depth;
    gaddr current,record,auxiliary,viewer,route;
    int zero;
} FlightWorking;
enum FlightChild {
    FC_NORMALISE_CONTROL,FC_ATTENUATE_X,FC_ATTENUATE_Z,FC_ATTENUATE_Y,
    FC_PROBE_CONTROL,FC_SAMPLE_TOUCHDOWN,FC_TOUCHDOWN_FAST_TONE,FC_TOUCHDOWN_SLOW_TONE,
    FC_RESET_CONTROL,FC_SAMPLE_TAKEOFF,FC_REQUEST_CONTROL,
    FC_RESET_MESSAGE,FC_NORMALISE_LENGTH,FC_CLASSIFY_LENGTH,FC_SIGHT_VECTOR,
    FC_CLASSIFY_RECORD,FC_ROUTE_FAULT,FC_REFRESH_VIEW,FC_REFRESH_SCENE,FC_PROJECT_VIEW,FC_SIGHT_RECORD,FC_ZONE_FAULT
};
enum FlightPhase {
    FC_VALUE_BYTE,FC_VALUE_WORD,FC_VALUE_LONG,FC_SPEED_BYTE,FC_SPEED_WORD,FC_SPEED_LONG,
    FC_TURN_BYTE,FC_TURN_WORD,FC_TURN_LONG,FC_X_BYTE,FC_X_WORD,FC_X_LONG,FC_Y_BYTE,FC_Y_WORD,FC_Y_LONG,
    FC_Z_WORD,FC_Z_LONG,FC_RATE_WORD,FC_RATE_LONG,FC_DEPTH_WORD,FC_DEPTH_LONG,
    FC_CURRENT,FC_RECORD,FC_AUXILIARY,FC_VIEWER,FC_ROUTE,
    FC_STORE_BYTE,FC_STORE_WORD,FC_STORE_LONG,FC_TEST_BYTE,FC_TEST_WORD,FC_TEST_LONG,
    FC_COMPARE_BYTE,FC_COMPARE_WORD,FC_COMPARE_LONG,FC_BIT_TEST,
    FC_VALUE_EXT_WORD,FC_VALUE_EXT_LONG,FC_SPEED_EXT_WORD,FC_SPEED_EXT_LONG,FC_TURN_EXT_LONG,
    FC_X_EXT_LONG,FC_Y_EXT_LONG,FC_Z_EXT_LONG,FC_DEPTH_EXT_LONG,
    FC_VALUE_AND_BYTE,FC_VALUE_AND_WORD,FC_VALUE_OR_BYTE,FC_VALUE_OR_WORD,
    FC_SPEED_AND_WORD,FC_TURN_AND_WORD,FC_X_AND_WORD,FC_Y_AND_WORD,
    FC_VALUE_ADD_BYTE,FC_VALUE_SUB_BYTE,FC_VALUE_ADD_WORD,FC_VALUE_SUB_WORD,FC_VALUE_ADD_LONG,FC_VALUE_SUB_LONG,
    FC_SPEED_ADD_WORD,FC_SPEED_SUB_BYTE,FC_SPEED_SUB_WORD,FC_SPEED_ADD_LONG,FC_SPEED_SUB_LONG,FC_SPEED_OR_BYTE,
    FC_TURN_ADD_WORD,FC_TURN_SUB_WORD,FC_TURN_ADD_LONG,FC_TURN_SUB_LONG,FC_X_ADD_BYTE,FC_X_SUB_BYTE,FC_X_ADD_WORD,FC_X_SUB_WORD,FC_X_ADD_LONG,FC_X_SUB_LONG,FC_Y_ADD_WORD,FC_Y_ADD_LONG,FC_Y_SUB_LONG,FC_Z_ADD_LONG,FC_Z_SUB_LONG,FC_DEPTH_ADD_LONG,
    FC_VALUE_ASR_WORD,FC_SPEED_ASR_WORD,FC_TURN_ASR_WORD,FC_VALUE_ASR_LONG,FC_SPEED_ASR_LONG,FC_TURN_ASR_LONG,FC_X_ASR_LONG,FC_Y_ASR_LONG,FC_Z_ASR_LONG,FC_DEPTH_ASR_LONG,
    FC_VALUE_ASL_WORD,FC_VALUE_ASL_LONG,FC_SPEED_ASL_WORD,FC_SPEED_ASL_LONG,FC_TURN_ASL_LONG,FC_X_ASL_WORD,FC_Z_ASL_WORD,
    FC_VALUE_LSR_WORD,FC_VALUE_SWAP,FC_TURN_SWAP,FC_X_SWAP,FC_Y_SWAP,FC_Z_SWAP,
    FC_VALUE_NEG_WORD,FC_VALUE_NEG_LONG,FC_SPEED_NEG_WORD,FC_SPEED_NEG_LONG,FC_TURN_NEG_WORD,FC_TURN_NEG_LONG,FC_X_NEG_WORD,FC_X_NEG_LONG,FC_Y_NEG_BYTE,FC_Y_NEG_WORD,FC_Y_NEG_LONG,FC_Z_NEG_WORD,FC_Z_NEG_LONG,FC_RATE_NEG_WORD,FC_DEPTH_NEG_WORD,
    FC_X_MULTIPLY,FC_Y_MULTIPLY,FC_TURN_MULTIPLY,FC_Z_MULTIPLY,FC_RATE_MULTIPLY,FC_DEPTH_MULTIPLY,
    FC_MEMORY_ADD_BYTE,FC_MEMORY_SUB_BYTE,FC_MEMORY_ADD_WORD,FC_MEMORY_SUB_WORD,FC_MEMORY_ADD_LONG,FC_MEMORY_SUB_LONG,
    FC_MEMORY_BIT_SET,FC_MEMORY_BIT_CLEAR,FC_MEMORY_BIT_CHANGE,
    FC_CONTROL_SETUP,FC_RESET_SLOTS,FC_NORMALISE_ARGUMENTS,FC_NORMALISE_DIVIDE,FC_NORMALISE_PRODUCTS,FC_NORMALISE_PUBLISH,
    FC_RANGE_COMPONENTS,FC_SIGHT_DIFFERENCE,FC_SIGHT_FACING,FC_SIGHT_ALIGNMENT,
    FC_EXCHANGE_Y_Z,FC_SAVE_MOTION,FC_RESTORE_MOTION,FC_MOTION_LOAD,FC_MOTION_STORE,FC_POSITION_LOAD,FC_REFERENCE_LOAD,
    FC_ROUTE_LOAD,FC_ROUTE_STORE,FC_REFERENCE_PAIR_LOAD,FC_REFERENCE_PAIR_STORE,FC_ZONE_VIEW_LOAD,
    FC_SELECTED_CONTROL_LOAD,FC_PROJECTED_VIEW_STORE
};
typedef struct {
    FlightWorking (*consume)(void *context,enum FlightChild child);
    void (*observe)(void *context,enum FlightPhase phase,uint32_t value,uint32_t other);
    FlightWorking (*divide_exception)(void *context);
    void *context;
} FlightHooks;
void advance_main_loop_flight_controls(gaddr frame,const FlightHooks *h);
FlightWorking advance_main_loop_flight_record(FlightWorking w,const FlightHooks *h);
void begin_main_loop_mission_reset(const FlightHooks *h);
void normalise_main_loop_control_vector(gaddr frame,const FlightHooks *h);
void classify_main_loop_record_range(FlightWorking w,const FlightHooks *h);
void update_main_loop_record_sight(FlightWorking w,const FlightHooks *h);
#endif
