#ifndef FA18_POSTFLIGHT_SCHEDULER_H
#define FA18_POSTFLIGHT_SCHEDULER_H
#include "memory.h"

enum PostflightSchedule {
    POSTFLIGHT_DISPATCH, POSTFLIGHT_MODE_THREE, POSTFLIGHT_MODE_FOUR,
    POSTFLIGHT_MODE_FIVE, POSTFLIGHT_MODE_SIX, POSTFLIGHT_MODE_SEVEN,
    POSTFLIGHT_MODE_NINE, POSTFLIGHT_MODE_125, POSTFLIGHT_MODE_OTHER,
    POSTFLIGHT_RESTORE_RECORD, POSTFLIGHT_PLAYER_READY
};
enum PostflightScheduleChild {
    SCHEDULE_SELECTION_GATE, SCHEDULE_THREE, SCHEDULE_FOUR, SCHEDULE_FIVE,
    SCHEDULE_SIX, SCHEDULE_SEVEN, SCHEDULE_NINE, SCHEDULE_125, SCHEDULE_OTHER,
    SCHEDULE_READY_GATE, SCHEDULE_PREPARE_FOUR, SCHEDULE_PREPARE_SEVEN,
    SCHEDULE_RESTORE_FIRST, SCHEDULE_RESTORE_SECOND
};
enum PostflightSchedulePhase {
    SCHEDULE_BYTE_TEST, SCHEDULE_WORD_TEST, SCHEDULE_BIT_TEST,
    SCHEDULE_BYTE_COMPARE, SCHEDULE_WORD_COMPARE, SCHEDULE_LONG_COMPARE,
    SCHEDULE_BYTE_STORE, SCHEDULE_WORD_STORE, SCHEDULE_LONG_STORE,
    SCHEDULE_BYTE_DECREMENT, SCHEDULE_WORD_DECREMENT, SCHEDULE_BIT_SET,
    SCHEDULE_WORD_OR, SCHEDULE_EVENT_BYTE, SCHEDULE_EVENT_WORD,
    SCHEDULE_EVENT_MASK_BYTE, SCHEDULE_EVENT_MASK_WORD, SCHEDULE_EVENT_ZERO,
    SCHEDULE_EVENT_ONE, SCHEDULE_EVENT_FOUR, SCHEDULE_EVENT_SEVEN,
    SCHEDULE_EVENT_DECREMENT, SCHEDULE_RECORD, SCHEDULE_PAIR,
    SCHEDULE_PAIR_SWAP, SCHEDULE_RESTORE_RECORD_SELECT, SCHEDULE_TARGET_RECORD,
    SCHEDULE_PLAYER_RECORD,
    SCHEDULE_POSITION_LOAD, SCHEDULE_REFERENCE_LOAD, SCHEDULE_DISTANCE_LIMIT,
    SCHEDULE_DISTANCE_SUBTRACT, SCHEDULE_DISTANCE_NEGATE, SCHEDULE_DISTANCE_COMPARE,
    SCHEDULE_TARGET_POSITION, SCHEDULE_TARGET_SUBTRACT_X, SCHEDULE_TARGET_SUBTRACT_Z,
    SCHEDULE_TARGET_NEGATE_X, SCHEDULE_TARGET_NEGATE_Z,
    SCHEDULE_TARGET_COMPARE_X, SCHEDULE_TARGET_COMPARE_Z,
    SCHEDULE_RESTORE_KIND, SCHEDULE_RESTORE_TABLE, SCHEDULE_RESTORE_VALUES,
    SCHEDULE_PREPARE_INDEX
};
typedef struct PostflightScheduleResult { uint32_t event; int zero; } PostflightScheduleResult;
typedef struct PostflightScheduleHooks {
    PostflightScheduleResult (*consume)(void *, enum PostflightScheduleChild, gaddr);
    void (*observe)(void *, enum PostflightSchedulePhase, uint32_t, uint32_t, gaddr);
    void *context;
} PostflightScheduleHooks;

/* Complete C09E06/C09E98/C09EC4/C0A002/C0A12E/C0A15C/C0A1E0/
 * C0A2F0/C0A334/C0A364/C0A3EA, including C0A3A6/C0A3C6 shared tails.
 * Leaf modes permit NULL hooks; a reached source child requires consume. */
void schedule_postflight(enum PostflightSchedule mode, uint16_t event,
                        gaddr record, const PostflightScheduleHooks *hooks);
#endif
