#ifndef FA18_SERVICE_DISPATCH_ADAPTER_H
#define FA18_SERVICE_DISPATCH_ADAPTER_H
enum {
    FA18_SERVICE_VBEAM,FA18_SERVICE_WAIT_BLIT,FA18_SERVICE_WAIT_BOVP,
    FA18_SERVICE_BLITTER_OWNERSHIP,FA18_SERVICE_EXEC_INTERRUPTS,
    FA18_SERVICE_EXEC_GET_MSG,FA18_SERVICE_POTGO,
    FA18_SERVICE_EXEC_FIND_TASK,FA18_SERVICE_EXEC_FIND_NAME,
    FA18_SERVICE_EXEC_LISTS,FA18_SERVICE_EXEC_PUT_MSG,
    FA18_SERVICE_EXEC_REPLY_WAIT_PORT,FA18_SERVICE_EXEC_SIGNALS,
    FA18_SERVICE_EXEC_SIGNAL_TRAPS,FA18_SERVICE_EXEC_TASK_PROTECTION,
    FA18_SERVICE_COUNT
};
void fa18_services_reset(void);
void fa18_service_enable(unsigned service,int enabled);
int fa18_services_step(void);
#endif
