#ifndef AMIGA_ABI_13_H
#define AMIGA_ABI_13_H
/* Guest byte offsets, cross-checked against the SDK declarations and pinned
 * 1.3 implementations. Never sizeof(host structs) or SDK header dependencies.
 * Later SDK-only fields are deliberately absent. */
enum {
    AMIGA_NODE_SUCC=0, AMIGA_NODE_PRED=4, AMIGA_NODE_PRIORITY=9, AMIGA_NODE_NAME=10,
    AMIGA_LIST_HEAD=0, AMIGA_LIST_TAIL=4, AMIGA_LIST_TAIL_PRED=8,
    AMIGA_NODE_TYPE=8, AMIGA_PORT_FLAGS=14, AMIGA_PORT_SIGNAL_BIT=15,
    AMIGA_INTERRUPT_DATA=14, AMIGA_INTERRUPT_CODE=18,
    AMIGA_EXEC_INT_VECTORS=0x54, AMIGA_INT_VECTOR_BYTES=12,
    AMIGA_INT_VECTOR_DATA=0, AMIGA_INT_VECTOR_CODE=4, AMIGA_INT_VECTOR_NODE=8,
    AMIGA_EXEC_SOFT_INTS=0x1B2, AMIGA_SOFT_INT_LIST_BYTES=16,
    AMIGA_PORT_SIGNAL_TASK=16, AMIGA_PORT_MESSAGES=20, AMIGA_MESSAGE_REPLY_PORT=14,
    AMIGA_TASK_FLAGS=14, AMIGA_TASK_STATE=15, AMIGA_TASK_SIGNALS_ALLOCATED=0x12,
    AMIGA_TASK_NEST_COUNTS=0x10, AMIGA_TASK_EXCEPT_DATA=0x26,
    AMIGA_TASK_EXCEPT_CODE=0x2A, AMIGA_TASK_SAVED_SP=0x36,
    AMIGA_TASK_SWITCH=0x42, AMIGA_TASK_LAUNCH=0x46,
    AMIGA_TASK_SIGNALS_WAIT=0x16, AMIGA_TASK_SIGNALS_RECEIVED=0x1A,
    AMIGA_TASK_SIGNALS_EXCEPT=0x1E, AMIGA_TASK_TRAPS_ALLOCATED=0x22,
    AMIGA_EXEC_RESCHEDULE_FLAGS=0x124,
    AMIGA_EXEC_IDLE_COUNT=0x118, AMIGA_EXEC_DISPATCH_COUNT=0x11C,
    AMIGA_EXEC_QUANTUM=0x120, AMIGA_EXEC_QUANTUM_REMAINING=0x122,
    AMIGA_EXEC_ATTN_FLAGS_LOW=0x129,
    AMIGA_EXEC_MEMORY_LIST=0x142,
    AMIGA_MEMORY_ATTRIBUTES=14, AMIGA_MEMORY_FIRST=16,
    AMIGA_MEMORY_LOWER=20, AMIGA_MEMORY_UPPER=24, AMIGA_MEMORY_FREE=28,
    AMIGA_CHUNK_NEXT=0, AMIGA_CHUNK_BYTES=4,
    AMIGA_EXEC_THIS_TASK=0x114, AMIGA_EXEC_ID_NEST_CNT=0x126,
    AMIGA_EXEC_TD_NEST_CNT=0x127, AMIGA_EXEC_TASK_READY=0x196,
    AMIGA_EXEC_TASK_WAIT=0x1A4, AMIGA_EXEC_FIND_NAME_LVO=-276
};
#endif
