#ifndef AMIGA_ABI_13_H
#define AMIGA_ABI_13_H
/* Guest byte offsets, cross-checked against the SDK declarations and pinned
 * 1.3 implementations. Never sizeof(host structs) or SDK header dependencies.
 * Later SDK-only fields are deliberately absent. */
enum {
    AMIGA_NODE_SUCC=0, AMIGA_NODE_PRED=4, AMIGA_NODE_PRIORITY=9, AMIGA_NODE_NAME=10,
    AMIGA_LIST_HEAD=0, AMIGA_LIST_TAIL=4, AMIGA_LIST_TAIL_PRED=8,
    AMIGA_NODE_TYPE=8, AMIGA_PORT_FLAGS=14, AMIGA_PORT_SIGNAL_BIT=15,
    AMIGA_PORT_SIGNAL_TASK=16, AMIGA_PORT_MESSAGES=20, AMIGA_MESSAGE_REPLY_PORT=14,
    AMIGA_TASK_FLAGS=14, AMIGA_TASK_STATE=15, AMIGA_TASK_SIGNALS_ALLOCATED=0x12,
    AMIGA_TASK_SIGNALS_WAIT=0x16, AMIGA_TASK_SIGNALS_RECEIVED=0x1A,
    AMIGA_TASK_SIGNALS_EXCEPT=0x1E, AMIGA_TASK_TRAPS_ALLOCATED=0x22,
    AMIGA_EXEC_RESCHEDULE_FLAGS=0x124,
    AMIGA_EXEC_THIS_TASK=0x114, AMIGA_EXEC_ID_NEST_CNT=0x126,
    AMIGA_EXEC_TD_NEST_CNT=0x127, AMIGA_EXEC_TASK_READY=0x196,
    AMIGA_EXEC_TASK_WAIT=0x1A4, AMIGA_EXEC_FIND_NAME_LVO=-276
};
#endif
