#ifndef AMIGA_EXEC_MEMORY_H
#define AMIGA_EXEC_MEMORY_H
#include "exec_task_services.h"
/* Verified memory-list semantics. Addresses and sizes are guest quantities;
 * allocation never uses host malloc, host pointers or captured OS memory. */
typedef enum {
    AMIGA_MEM_FLOW, AMIGA_MEM_EQ, AMIGA_MEM_NE, AMIGA_MEM_HI, AMIGA_MEM_LS,
    AMIGA_MEM_CS, AMIGA_MEM_CC, AMIGA_MEM_GE, AMIGA_MEM_GT,
    AMIGA_MEM_SAVE_REGISTERS, AMIGA_MEM_RESTORE_REGISTERS, AMIGA_MEM_RETURN,
    AMIGA_MEM_TEST_SIZE, AMIGA_MEM_ROUND_ADD, AMIGA_MEM_ROUND_MASK_BYTE,
    AMIGA_MEM_RESULT_ZERO, AMIGA_MEM_COMPARE_TOTAL, AMIGA_MEM_BEGIN_FREE_LINK,
    AMIGA_MEM_NEXT_FREE_CHUNK, AMIGA_MEM_CHUNK_FROM_RESULT, AMIGA_MEM_COMPARE_CHUNK_SIZE,
    AMIGA_MEM_FOLLOW_CHUNK, AMIGA_MEM_SPLIT_ADDRESS, AMIGA_MEM_COPY_SPLIT_LINK,
    AMIGA_MEM_LOAD_CHUNK_SIZE, AMIGA_MEM_SUBTRACT_SIZE, AMIGA_MEM_STORE_SPLIT_SIZE,
    AMIGA_MEM_LINK_SPLIT, AMIGA_MEM_UNLINK_CHUNK, AMIGA_MEM_SUBTRACT_TOTAL,
    AMIGA_MEM_RESULT_ADDRESS, AMIGA_MEM_RETURN_RESULT,
    AMIGA_MEM_ADDRESS_OFFSET, AMIGA_MEM_ALIGNMENT_MASK, AMIGA_MEM_ALIGN_ADDRESS,
    AMIGA_MEM_EXCHANGE_ADDRESS, AMIGA_MEM_ADDRESS_REMAINDER, AMIGA_MEM_ADD_REMAINDER,
    AMIGA_MEM_ALIGN_SIZE, AMIGA_MEM_COMPARE_FREE_ADDRESS, AMIGA_MEM_FOLLOW_RESULT,
    AMIGA_MEM_HEADER_LINK_OFFSET, AMIGA_MEM_ADD_HEADER_ADDRESS, AMIGA_MEM_COMPARE_LINK_ADDRESS,
    AMIGA_MEM_LOAD_LEFT_SIZE, AMIGA_MEM_LEFT_END, AMIGA_MEM_COMPARE_LEFT_END,
    AMIGA_MEM_COPY_LEFT_LINK, AMIGA_MEM_LINK_FREED_CHUNK, AMIGA_MEM_STORE_FREED_SIZE,
    AMIGA_MEM_EXTEND_LEFT, AMIGA_MEM_USE_LEFT_CHUNK, AMIGA_MEM_TEST_NEXT_CHUNK,
    AMIGA_MEM_CHUNK_END, AMIGA_MEM_COMPARE_RIGHT_ADDRESS, AMIGA_MEM_USE_RIGHT_CHUNK,
    AMIGA_MEM_COPY_RIGHT_LINK, AMIGA_MEM_EXTEND_RIGHT, AMIGA_MEM_ADD_TOTAL,
    AMIGA_MEM_ALERT_NUMBER, AMIGA_MEM_EXEC_BASE,
    AMIGA_MEM_TASK_DEPTH_UP, AMIGA_MEM_SAVE_SIZE, AMIGA_MEM_SAVE_REQUIREMENTS,
    AMIGA_MEM_BEGIN_HEADERS_A2, AMIGA_MEM_NEXT_HEADER_A2, AMIGA_MEM_TEST_HEADER_A2,
    AMIGA_MEM_LOAD_ATTRIBUTES_A2, AMIGA_MEM_MASK_ATTRIBUTES_D2, AMIGA_MEM_COMPARE_ATTRIBUTES_D2,
    AMIGA_MEM_USE_HEADER_A2, AMIGA_MEM_RESTORE_SIZE, AMIGA_MEM_NO_ALLOCATION,
    AMIGA_MEM_TEST_CLEAR, AMIGA_MEM_CLEAR_VALUE, AMIGA_MEM_CLEAR_ROUND,
    AMIGA_MEM_CLEAR_WORD_COUNT, AMIGA_MEM_CLEAR_ADDRESS, AMIGA_MEM_CLEAR_WORD,
    AMIGA_MEM_NEXT_CLEAR_WORD, AMIGA_MEM_SWAP_WORD_COUNT, AMIGA_MEM_TEST_WORD_COUNT,
    AMIGA_MEM_DECREMENT_WORD_COUNT,
    AMIGA_MEM_BEGIN_HEADERS_A0, AMIGA_MEM_NEXT_HEADER_A0, AMIGA_MEM_TEST_HEADER_A0,
    AMIGA_MEM_COMPARE_LOWER, AMIGA_MEM_COMPARE_UPPER, AMIGA_MEM_LOAD_ATTRIBUTES_A0,
    AMIGA_MEM_BEGIN_HEADERS_A1, AMIGA_MEM_NEXT_HEADER_A1, AMIGA_MEM_TEST_HEADER_A1,
    AMIGA_MEM_LOAD_ATTRIBUTES_A1, AMIGA_MEM_MASK_ATTRIBUTES_D1, AMIGA_MEM_COMPARE_ATTRIBUTES_D1,
    AMIGA_MEM_TEST_LARGEST, AMIGA_MEM_ACCUMULATE_FREE, AMIGA_MEM_FIRST_CHUNK_D0,
    AMIGA_MEM_CHUNK_FROM_D0, AMIGA_MEM_COMPARE_LARGEST, AMIGA_MEM_REMEMBER_LARGEST,
    AMIGA_MEM_LOAD_LARGEST, AMIGA_MEM_NEXT_CHUNK_D0,
    AMIGA_MEM_ABSOLUTE_OFFSET, AMIGA_MEM_MASK_ABSOLUTE_OFFSET,
    AMIGA_MEM_ALIGN_ABSOLUTE_ADDRESS, AMIGA_MEM_ADD_ABSOLUTE_OFFSET,
    AMIGA_MEM_REMEMBER_ABSOLUTE_ADDRESS, AMIGA_MEM_ABSOLUTE_END_START,
    AMIGA_MEM_ABSOLUTE_END_SIZE, AMIGA_MEM_LOAD_ABSOLUTE_CHUNK_SIZE,
    AMIGA_MEM_ABSOLUTE_CHUNK_END, AMIGA_MEM_COMPARE_ABSOLUTE_END,
    AMIGA_MEM_COMPARE_ABSOLUTE_START, AMIGA_MEM_ABSOLUTE_REMAINDER,
    AMIGA_MEM_ABSOLUTE_SUCCESSOR, AMIGA_MEM_ABSOLUTE_SPLIT_ADDRESS,
    AMIGA_MEM_COPY_ABSOLUTE_SPLIT_LINK, AMIGA_MEM_LINK_ABSOLUTE_SPLIT,
    AMIGA_MEM_STORE_ABSOLUTE_SPLIT_SIZE, AMIGA_MEM_ABSOLUTE_LEFT_SIZE,
    AMIGA_MEM_NEGATE_LEFT_SIZE, AMIGA_MEM_STORE_ABSOLUTE_LEFT_SIZE,
    AMIGA_MEM_LINK_ABSOLUTE_SUCCESSOR, AMIGA_MEM_ABSOLUTE_RESULT,
    AMIGA_MEM_PHASE_COUNT
} AmigaExecMemoryPhase;
typedef struct {
    int branch_taken,returned,dbra_continues;
    unsigned transferred_longs;
    uint32_t return_pc;
} AmigaExecMemoryEffect;
/* arg is a normal-order register mask for MOVEM, or an original alert number.
 * Timing, guest calls and their continuations belong to the CPU/bus adapter. */
int amiga_exec_memory_step(AmigaExecMemoryPhase,unsigned,AmigaExecTaskState *,
                           const AmigaExecTaskBus *,AmigaExecMemoryEffect *);
#endif
