#ifndef AMIGA_EXEC_INTERRUPT_SERVICES_H
#define AMIGA_EXEC_INTERRUPT_SERVICES_H
#include "exec_context.h"
/* Guest interrupt vectors, server chains and deferred soft-interrupt queues.
 * No host interrupts, SDK, ROM addresses, CPU core or game state. The adapter
 * supplies bus phases, interrupt acceptance, SR changes and callback transfers. */
typedef enum {
    AMIGA_INT_VECTOR_INDEX, AMIGA_INT_VECTOR_ADDRESS, AMIGA_INT_OLD_NODE,
    AMIGA_INT_INSTALL_NODE, AMIGA_INT_COPY_DATA, AMIGA_INT_COPY_CODE,
    AMIGA_INT_NO_HANDLER, AMIGA_INT_CLEAR_VECTOR, AMIGA_INT_SAVE_D2,
    AMIGA_INT_RESTORE_D2, AMIGA_INT_SAVE_NUMBER, AMIGA_INT_NUMBER_D1,
    AMIGA_INT_SERVER_LIST, AMIGA_INT_SET_ENABLE_BIT, AMIGA_INT_ENABLE_WORD,
    AMIGA_INT_CLEAR_ENABLE_BIT, AMIGA_INT_DISABLE_WORD, AMIGA_INT_LIST_FROM_D1,
    AMIGA_INT_LIST_EMPTY, AMIGA_INT_PUSH_CLEAR_MASK, AMIGA_INT_SAVE_A2,
    AMIGA_INT_RESTORE_A2, AMIGA_INT_FIRST_SERVER, AMIGA_INT_SERVER_SUCCESSOR,
    AMIGA_INT_NODE_CALLBACK, AMIGA_INT_NEXT_SERVER, AMIGA_INT_ACK_SAVED_MASK,
    AMIGA_INT_COMPARE_QUEUED, AMIGA_INT_QUEUE_NODE, AMIGA_INT_PRIORITY_BYTE,
    AMIGA_INT_PRIORITY_GROUP, AMIGA_INT_SIGN_PRIORITY, AMIGA_INT_SOFT_QUEUE,
    AMIGA_INT_SOFT_PENDING, AMIGA_INT_CLEAR_SOFT_PENDING,
    AMIGA_INT_SOFT_HEAD, AMIGA_INT_SOFT_SUCCESSOR, AMIGA_INT_UNLINK_SOFT,
    AMIGA_INT_EXCHANGE_NODE, AMIGA_INT_LINK_SOFT_SUCCESSOR,
    AMIGA_INT_NODE_FROM_D0, AMIGA_INT_CALLBACK_NODE_TYPE, AMIGA_INT_SOFT_SCAN,
    AMIGA_INT_SOFT_NEXT_QUEUE, AMIGA_INT_NEXT_PRIORITY,
    AMIGA_INT_CUSTOM_BASE, AMIGA_INT_ENABLED_WORD, AMIGA_INT_PENDING_WORD,
    AMIGA_INT_TEST_PENDING, AMIGA_INT_VECTOR_CALLBACK, AMIGA_INT_AUDIO_MASK,
    AMIGA_INT_MASK_ENABLED_WORD, AMIGA_INT_REQUEST_WORD, AMIGA_INT_PHASE_COUNT
} AmigaExecInterruptPhase;
typedef struct { unsigned transferred_longs; int bit_below16,dbra_continues; } AmigaExecInterruptEffect;
int amiga_exec_interrupt_step(AmigaExecInterruptPhase,unsigned arg,AmigaExecTaskState *,
                              const AmigaExecTaskBus *,AmigaExecInterruptEffect *);
#endif
