#ifndef AMIGA_EXEC_SCHEDULER_H
#define AMIGA_EXEC_SCHEDULER_H
#include "exec_context.h"
/* Guest task dispatch and exception delivery, with no ROM addresses, SDK,
 * interpreter, host task scheduler or captured OS state. One resumable phase
 * per observable operation; the embedding CPU owns SR/USP/RTE/STOP and calls. */
typedef enum {
    AMIGA_SCHED_SAVED_SUPERVISOR, AMIGA_SCHED_EXEC_BASE,
    AMIGA_SCHED_TEST_TASK_EXCEPTION, AMIGA_SCHED_TEST_TASK_SWITCH,
    AMIGA_SCHED_TEST_RESCHEDULE_BIT, AMIGA_SCHED_CLEAR_RESCHEDULE_BIT,
    AMIGA_SCHED_SET_RESCHEDULE_BIT, AMIGA_SCHED_READY_EMPTY,
    AMIGA_SCHED_READY_HEAD_A0, AMIGA_SCHED_READY_PRIORITY,
    AMIGA_SCHED_COMPARE_PRIORITY, AMIGA_SCHED_PUSH_SAVED_A6,
    AMIGA_SCHED_INSTALL_SWITCH_RETURN, AMIGA_SCHED_LOAD_NEST_COUNTS,
    AMIGA_SCHED_RESET_NEST_COUNTS, AMIGA_SCHED_SAVE_CALLER_A5,
    AMIGA_SCHED_SAVE_STATUS, AMIGA_SCHED_SAVE_PC,
    AMIGA_SCHED_CURRENT_TASK_A3, AMIGA_SCHED_SAVE_TASK_NEST_COUNTS,
    AMIGA_SCHED_SAVE_TASK_SP, AMIGA_SCHED_LOAD_SWITCH_CALLBACK,
    AMIGA_SCHED_READY_HEAD_A3, AMIGA_SCHED_READY_SUCCESSOR,
    AMIGA_SCHED_INCREMENT_COUNTER, AMIGA_SCHED_REMOVE_READY_HEAD,
    AMIGA_SCHED_READY_SUCCESSOR_A1, AMIGA_SCHED_LINK_READY_SUCCESSOR,
    AMIGA_SCHED_INSTALL_CURRENT_TASK, AMIGA_SCHED_RESET_QUANTUM,
    AMIGA_SCHED_SET_TASK_STATE, AMIGA_SCHED_RESTORE_NEST_COUNTS,
    AMIGA_SCHED_LOAD_TASK_FLAGS, AMIGA_SCHED_CALLBACK_FLAGS,
    AMIGA_SCHED_LOAD_TASK_SP_A5, AMIGA_SCHED_RESUMED_USP_A2,
    AMIGA_SCHED_PUSH_TASK_PC, AMIGA_SCHED_PUSH_TASK_STATUS,
    AMIGA_SCHED_TEST_CALLBACK_BIT, AMIGA_SCHED_SAVE_CALLBACK_FLAGS,
    AMIGA_SCHED_RESTORE_CALLBACK_FLAGS, AMIGA_SCHED_LOAD_LAUNCH_CALLBACK,
    AMIGA_SCHED_CLEAR_TASK_EXCEPTION, AMIGA_SCHED_LOAD_RECEIVED,
    AMIGA_SCHED_EXCEPTION_SIGNALS, AMIGA_SCHED_CLEAR_SIGNALS,
    AMIGA_SCHED_LOAD_TASK_SP_A1, AMIGA_SCHED_PUSH_TASK_HEADER,
    AMIGA_SCHED_PUSH_EXCEPTION_RETURN, AMIGA_SCHED_TEST_CPU_FLAG,
    AMIGA_SCHED_PUSH_FRAME_FORMAT, AMIGA_SCHED_PUSH_EXCEPTION_CODE,
    AMIGA_SCHED_PUSH_USER_STATUS, AMIGA_SCHED_EXCEPTION_DATA,
    AMIGA_SCHED_ADD_RETURNED_SIGNALS, AMIGA_SCHED_RESTORE_TASK_HEADER,
    AMIGA_SCHED_SAVE_EXCEPTION_SP, AMIGA_SCHED_PHASE_COUNT
} AmigaExecSchedulerPhase;
int amiga_exec_scheduler_step(AmigaExecSchedulerPhase,unsigned arg,
                              AmigaExecTaskState *,const AmigaExecTaskBus *);
#endif
