#ifndef FA18_RECOMP_PORTS_H
#define FA18_RECOMP_PORTS_H

/* Stage D: hand-written C routines replacing generated ones.
 *
 * Each port has a glue function (port/game/glue/) that is entered exactly
 * where the original routine is: at its first instruction, after a JSR/BSR
 * or a registered tail jump. The glue reads the routine's inputs from
 * the 68000 registers and game memory, calls the hand-written C in
 * port/game/, stores the outputs and register effects the original leaves,
 * then performs the RTS. It returns FA18_RET. A timing-sensitive bridge can
 * instead provide one-instruction steps and retain a source-stack
 * continuation until its eventual RTS; those steps run between chipset
 * service boundaries and may suspend for children, interrupts or frames.
 *
 * Modes:
 *   OFF     generated code only (the reference).
 *   SHADOW  every call runs the generated routine and the glue on the same
 *           state and compares registers, flags and memory writes; the game
 *           continues on the generated result. Proof mode.
 *   ON      glue only.
 */

#include <stdint.h>
#include <stddef.h>

typedef int (*FA18PortGlue)(void);
/* Complete one source instruction in a timing-sensitive glue bridge.
 * Returns 1 when handled, 0 outside that bridge. No opcode handler is run. */
typedef int (*FA18PortStep)(void);
/* Some owners jump to shared tails with child routines between their source
 * regions. The predicate selects owned instruction boundaries within the
 * outer range; absent predicates retain the contiguous-range contract. */
typedef int (*FA18PortStepOwns)(uint32_t pc);

typedef struct {
    uint32_t entry;       /* original routine address */
    FA18PortGlue glue;
    const char *name;     /* the C function it calls */
    int cycles;           /* fixed ON charge for whole-call glue; unused with step */
    uint32_t tail_from;   /* optional source address of a verified tail JMP */
    FA18PortStep step;    /* optional resumable bridge, with exact bus/cycle timing */
    uint32_t step_end;    /* exclusive end of the outer source instruction range */
    int shadow_busy_reads; /* proof bits: 1 DMACONR, 2 JOY0DAT/JOY1DAT/POTINP; source read order checked */
    uint32_t step_start;   /* optional shared source prefix before entry */
    FA18PortStepOwns step_owns; /* optional noncontiguous instruction ownership */
} FA18Port;

extern const FA18Port fa18_ports[];
extern const int fa18_port_count;

/* Generated by tools/recomp/liveness.py: what a caller may read after the
 * call that returns to `ret`. regs: bit 0 = D0 (low word) .. bit 7 = D7,
 * bit 8 = A0 .. bit 15 = A7; high: D0-D7 high words; flags: bit 0 = X, then
 * N, Z, V, C. Sorted by `ret`. */
typedef struct { uint32_t ret; uint16_t regs; uint8_t high; uint8_t flags; } FA18CallLiveness;
extern const FA18CallLiveness fa18_call_liveness[];
extern const int fa18_call_liveness_count;

typedef enum { FA18_PORTS_OFF, FA18_PORTS_ON, FA18_PORTS_SHADOW, FA18_PORTS_SANDBOX } FA18PortMode;

void fa18_ports_init(FA18PortMode mode, const char *only);
/* Dispatch a registered original owner absent from the seeded translation.
 * Returns 1 only when it handled the entry; reference execution stays in the
 * existing runtime. Selection and call/tail guards match translated ports. */
int fa18_ports_enter_source_only(int via_call,int *result);
void fa18_ports_note_source_write(uint32_t address,int size);
/* Resume an active stepped call after chipset work, a child or an interrupt.
 * Called at an already-serviced instruction boundary; 1 means it advanced. */
int fa18_ports_resume_step(void);
/* A retained C owner, rather than an original instruction, owns this return. */
int fa18_ports_native_boundary_ready(void);
/* Read-only continuation count for bounded source timing audits. */
size_t fa18_ports_active_steps(void);
/* Schedule a C child selected by its parent's source call site. The copied
 * arguments survive chipset service/interrupts. PC/SP only guard resumption
 * of this compatibility boundary; they do not select the C callee. Returns
 * zero in held-event proofs/isolated step fixtures, which retain reference
 * child dispatch. The existing atomic timing debt is explicit in cycles. */
typedef int (*FA18NativeChild)(const void *arguments);
int fa18_ports_schedule_native_child(FA18NativeChild child, const void *arguments,
                                     size_t size, int cycles);
/* An executing C continuation can wait for an existing source child. Its
 * copied payload may retain mutable C state until FA18_RET. Return
 * FA18_EXIT_DISPATCH after arming this guard; the runtime executes the child
 * before invoking the continuation again. Do not dispatch a child recursively
 * inside the callback. C state selects the phase; PC/SP only guard resumption. */
void fa18_ports_native_child_wait(uint32_t return_pc, uint32_t return_sp);
/* SHADOW only: after each compared call, overwrite what the liveness table
 * declares dead. The run must still end like the plain generated run. */
void fa18_ports_set_poison(int on);
/* Writes the per-port SHADOW results (calls, matches, mismatches, mean
 * cycles) as JSON; returns the number of mismatching calls. */
long fa18_ports_report(const char *path);

/* Per-routine call counts, for tools/recomp/inventory.py --profile. */
int fa18_recomp_write_profile(const char *path);
/* Observe an actual C-to-C game call, without consulting guest PC or stack.
 * Profiling only; omitted when --profile is inactive. */
void fa18_ports_note_native_edge(uint32_t caller, uint32_t callee);
/* Observed call edges [[return address, routine], ...] for the liveness pass. */
int fa18_recomp_write_edges(const char *path);

#endif
