#ifndef FA18_RECOMP_PORTS_H
#define FA18_RECOMP_PORTS_H

/* Stage D: hand-written C routines replacing generated ones.
 *
 * Each port has a glue function (port/game/glue/) that is entered exactly
 * where the original routine is: at its first instruction, after a JSR/BSR
 * or a registered tail jump. The glue reads the routine's inputs from
 * the 68000 registers and game memory, calls the hand-written C in
 * port/game/, stores the outputs and register effects the original leaves,
 * then performs the RTS. It returns FA18_RET.
 *
 * Modes:
 *   OFF     generated code only (the reference).
 *   SHADOW  every call runs the generated routine and the glue on the same
 *           state and compares registers, flags and memory writes; the game
 *           continues on the generated result. Proof mode.
 *   ON      glue only.
 */

#include <stdint.h>

typedef int (*FA18PortGlue)(void);

typedef struct {
    uint32_t entry;       /* original routine address */
    FA18PortGlue glue;
    const char *name;     /* the C function it calls */
    int cycles;           /* CPU cycles charged in ON mode (measured in SHADOW) */
    uint32_t tail_from;   /* optional source address of a verified tail JMP */
} FA18Port;

extern const FA18Port fa18_ports[];
extern const int fa18_port_count;

/* Generated by tools/recomp/liveness.py: what a caller may read after the
 * call that returns to `ret`. regs: bit 0 = D0 (low word) .. bit 7 = D7,
 * bit 8 = A0 .. bit 15 = A7; high: D0-D7 high words; flags: bit 0 = X, then
 * N, Z, V, C. Sorted by `ret`. */
typedef struct { uint32_t ret; uint16_t regs; uint8_t high; uint8_t flags; } FA18CallLiveness;
extern const FA18CallLiveness fa18_call_liveness[];
extern const int fa18_call_liveness_count;

typedef enum { FA18_PORTS_OFF, FA18_PORTS_ON, FA18_PORTS_SHADOW, FA18_PORTS_SANDBOX } FA18PortMode;

void fa18_ports_init(FA18PortMode mode, const char *only);
/* SHADOW only: after each compared call, overwrite what the liveness table
 * declares dead. The run must still end like the plain generated run. */
void fa18_ports_set_poison(int on);
/* Writes the per-port SHADOW results (calls, matches, mismatches, mean
 * cycles) as JSON; returns the number of mismatching calls. */
long fa18_ports_report(const char *path);

/* Per-routine call counts, for tools/recomp/inventory.py --profile. */
int fa18_recomp_write_profile(const char *path);
/* Observed call edges [[return address, routine], ...] for the liveness pass. */
int fa18_recomp_write_edges(const char *path);

#endif
