#ifndef FA18_CONTEXT_COMMAND_TYPES_H
#define FA18_CONTEXT_COMMAND_TYPES_H

enum ContextCommandChild {
    CONTEXT_COMMAND_LOCAL_TO_WORLD, CONTEXT_COMMAND_SET_OBSERVER,
    CONTEXT_COMMAND_MAP_VOICES, CONTEXT_COMMAND_REQUEST_VOICES
};

#endif
