"""Generate the Slow-RAM Ghidra function-entry coverage ledger.

Function inventories are structural Ghidra evidence.  An entry is counted as
represented only when its address falls inside a byte-exact observed assembly
slice; an exact match means the slice starts at that entry.
"""
import argparse
import json
from pathlib import Path

import coverage as cov

ROOT = Path(__file__).resolve().parents[1]
SLOW_BASE = 0xC00000
SLOW_END = 0xC80000


def function_entries(pcode_root):
    """Return one structural entry per Slow-RAM address across all exports."""
    entries = {}
    for path in sorted(pcode_root.glob('*/functions.json')):
        for row in json.loads(path.read_text()):
            address = row.get('address')
            if not isinstance(address, int) or not SLOW_BASE <= address < SLOW_END:
                continue
            entry = entries.setdefault(address, {'row': row, 'exports': []})
            entry['exports'].append(path.parent.name)
    return entries


def render(entries, slices, exports, semantic_contracts):
    ranges = [(row['address'], row['address'] + len(row['assembled']))
              for row in slices]
    exact_starts = {row['address'] for row in slices}
    addresses = set(entries)
    represented = {address for address in addresses
                   if any(start <= address < end for start, end in ranges)}
    exact = addresses & exact_starts
    total = len(addresses)
    unrepresented = sorted(
        (address for address in addresses if address not in represented),
        key=lambda address: (-entries[address]['row'].get('body_bytes', 0), address))
    priority_rows = [
        f"| `${address:06X}` | {entries[address]['row'].get('body_bytes', 'unknown')} | "
        f"{len(entries[address]['exports'])} | `{entries[address]['row'].get('name', 'unknown')}` |"
        for address in unrepresented[:25]]

    return f"""# Ghidra function-entry coverage

Generated by `scripts/generate_ghidra_function_coverage.py` from every
`pcode/raw/*/functions.json` inventory and exact assembled ranges in
`source_amiga/observed/`.

| Measure | Count | Meaning |
|---|---:|---|
| P-code exports containing a function inventory | {exports} | Independent capture packets; entries recur across packets. |
| Distinct Slow-RAM Ghidra function entries | {total} | Union by entry address. All retain Ghidra's `structural` classification. |
| Entries with an exact source-slice entry address | {len(exact)} | A readable, byte-exact source slice starts at the same address. This does not imply its entire Ghidra function body is reconstructed. |
| Entries represented within any byte-exact source range | {len(represented)} | Includes entries reached through an adjacent source slice. |
| Entries with no byte-exact source representation | {total - len(represented)} | Require source reconstruction or a range extension. |
| Entries with a bounded behavioural routine contract | {semantic_contracts} | Evidence-backed project classifications in `analysis/semantics.json`; this is not a claim that all are exact-entry matches. |
| Entries without an exact source-slice entry | {total - len(exact)} | Either require an entry reconstruction or are represented only by an adjacent source slice. |

## Largest observed entries without exact source

This is a structural reconstruction queue, sorted by Ghidra's body-byte estimate
then address. `Exports` is the number of P-code inventories containing the
entry, not a dynamic call count or semantic-confidence measure. Smaller entries
or entries represented through an adjacent slice may be better candidates when
they close a verified call/return boundary.

| Entry | Ghidra body bytes | Exports | Structural inventory name |
| --- | ---: | ---: | --- |
{chr(10).join(priority_rows)}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--pcode-root', type=Path, default=ROOT / 'pcode' / 'raw')
    parser.add_argument('--source-dir', type=Path, default=ROOT / 'source_amiga' / 'observed')
    parser.add_argument('--output', type=Path,
                        default=ROOT / 'analysis' / 'ghidra_function_coverage.md')
    args = parser.parse_args()

    entries = function_entries(args.pcode_root)
    slices, _ = cov.assemble_slices(args.source_dir)
    semantics = json.loads((ROOT / 'analysis' / 'semantics.json').read_text())
    exports = len(list(args.pcode_root.glob('*/functions.json')))
    output = render(entries, slices, exports, semantics['behavioral_routines'])
    args.output.write_text(output)
    print(f'wrote {args.output.relative_to(ROOT)}: {len(entries)} Slow-RAM entries')


if __name__ == '__main__':
    main()
