"""Checksum local ADF variants with the runtime reader; store identities only."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", type=Path, default=Path("D:/amiga"))
    parser.add_argument("--runner", type=Path, default=ROOT / "build/recomp/fa18_romfree.exe")
    parser.add_argument("--output", type=Path, default=ROOT / "analysis/adf_versions.json")
    parser.add_argument("--catalog", type=Path, default=ROOT / "port/romfree/adf_versions.inc")
    args = parser.parse_args()
    paths = sorted(p for p in args.directory.rglob("*") if p.is_file() and p.suffix.lower() == ".adf")
    if not paths:
        raise FileNotFoundError(f"No ADFs in {args.directory}")
    rows = []
    for path in paths:
        before = hashlib.sha256(path.read_bytes()).hexdigest()
        result = subprocess.run([str(args.runner.resolve()), "--identify-adf", str(path.resolve())],
                                capture_output=True, text=True, check=True)
        info = json.loads(result.stdout)
        assert info["disk_sha256"] == before == hashlib.sha256(path.read_bytes()).hexdigest()
        rows.append(dict(file=path.name, size=path.stat().st_size, **info))
        print(f"{'SUPPORTED' if info['supported'] else 'unsupported'}: {path.name}")
    manifest = dict(scope="Disk SHA-256 identities; supported means exact verified executable, not complete gameplay acceptance", images=rows)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(manifest, indent=2) + "\n")
    # Filename spelling is catalog metadata only; detection uses the digest.
    unique = {}
    for row in rows:
        unique.setdefault(row["disk_sha256"], row["file"])
    args.catalog.write_text("/* Generated by scripts/inventory_adf_versions.py; identities only, no disk bytes. */\n" +
                            "".join("    {" + json.dumps(digest) + "," + json.dumps(name) + "},\n" for digest, name in unique.items()))
    print(f"{len(rows)} images, {sum(row['supported'] for row in rows)} compatible executables")


if __name__ == "__main__":
    main()
