"""Rank CODE absent from P-code exports as capture targets and write analysis/capture_targets.md.

Reconstruction cannot outrun scenario coverage: a segment absent from all P-code
exports needs a new export before this inventory can support a P-code-backed
behavioural contract. Independent bounded traces can still prove narrow runtime
facts, so this report must not call such a segment globally "unexecuted".
This ranks P-code gaps so recording effort can be aimed rather than guessed.

Segments are ordered by size. A segment reached by a reconstructed branch or call
but never observed running is listed first: its caller is already understood, so
one scenario that takes that branch converts it directly into traceable evidence.
"""
import argparse
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import coverage as cov

ROOT = Path(__file__).resolve().parents[1]


def partial_threshold(row):
    """Fraction of a segment's bytes seen executing."""
    return row['executed'] / row['size'] if row['size'] else 0.0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path,
                        default=ROOT / 'analysis' / 'capture_targets.md')
    parser.add_argument('--limit', type=int, default=25,
                        help='rows per table')
    args = parser.parse_args()

    executed, exports = cov.observed_bytes()
    segments = cov.resolved_code_segments()
    data_refs, flow_refs = cov.symbol_references()
    rows = cov.classify_segments(segments, executed, data_refs, flow_refs)

    reachable = sorted((row for row in rows
                        if row['verdict'] == 'code-branch-target'),
                       key=lambda row: -row['size'])
    dark = sorted((row for row in rows if row['verdict'] == 'unclassified'),
                  key=lambda row: -row['size'])
    partial = sorted((row for row in rows
                      if row['verdict'] == 'code-executed' and partial_threshold(row) < 0.5),
                     key=lambda row: -(row['size'] - row['executed']))

    lines = []
    lines.append('# Capture targets')
    lines.append('')
    lines.append(f'Generated by `scripts/plan_captures.py` on {date.today().isoformat()} '
                 f'from {exports} P-code exports.')
    lines.append('')
    lines.append(f'{len(executed):,} bytes of the {sum(r["size"] for r in rows):,} resolved CODE '
                 f'bytes occur in the {exports} imported P-code exports. Everything below '
                 f'is a P-code coverage gap. A dedicated bounded trace may independently '
                 f'prove a narrow runtime contract, but does not make the bytes part of this '
                 f'P-code inventory.')
    lines.append('')

    lines.append('## Reached by reconstructed code but absent from P-code exports')
    lines.append('')
    lines.append('A reconstructed slice branches or calls into these, so the entry is already '
                 'located. Check dedicated trace notes before calling one unexecuted; a '
                 'new P-code export remains the highest-value capture target.')
    lines.append('')
    lines.append('| Segment | Runtime range | Bytes | Call/branch references |')
    lines.append('|---:|---|---:|---:|')
    for row in reachable[:args.limit]:
        lines.append(f'| {row["segment"]} | `${row["base"]:06X}-${row["base"] + row["size"]:06X}` '
                     f'| {row["size"]:,} | {row["flow_refs"]} |')
    lines.append('')
    lines.append(f'Total: {len(reachable)} segments, '
                 f'{sum(row["size"] for row in reachable):,} bytes.')
    lines.append('')

    lines.append('## Partially exercised')
    lines.append('')
    lines.append('These have executed, but under half their bytes. A different scenario '
                 'through the same subsystem is likely to reach the remainder.')
    lines.append('')
    lines.append('| Segment | Runtime range | Bytes | Executed | Unseen |')
    lines.append('|---:|---|---:|---:|---:|')
    for row in partial[:args.limit]:
        lines.append(f'| {row["segment"]} | `${row["base"]:06X}-${row["base"] + row["size"]:06X}` '
                     f'| {row["size"]:,} | {row["executed"]:,} ({partial_threshold(row) * 100:.0f}%) '
                     f'| {row["size"] - row["executed"]:,} |')
    lines.append('')
    lines.append(f'Total unseen in partially exercised segments: '
                 f'{sum(row["size"] - row["executed"] for row in partial):,} bytes.')
    lines.append('')

    lines.append('## Dark')
    lines.append('')
    lines.append('Absent from P-code exports and never referenced by reconstructed source. Each '
                 'is either a subsystem no imported export has entered, or data the linker '
                 'emitted as CODE; the two are indistinguishable until a relevant export '
                 'or other evidence reaches it.')
    lines.append('')
    lines.append('| Segment | Runtime range | Bytes |')
    lines.append('|---:|---|---:|')
    for row in dark[:args.limit]:
        lines.append(f'| {row["segment"]} | `${row["base"]:06X}-${row["base"] + row["size"]:06X}` '
                     f'| {row["size"]:,} |')
    lines.append('')
    lines.append(f'Total: {len(dark)} segments, {sum(row["size"] for row in dark):,} bytes'
                 + (f' (showing largest {args.limit})' if len(dark) > args.limit else '') + '.')
    lines.append('')

    args.output.write_text('\n'.join(lines))
    print(f'wrote {args.output.relative_to(ROOT)}')
    print(f'  reachable-but-unexecuted: {len(reachable)} segments, '
          f'{sum(row["size"] for row in reachable):,} bytes')
    print(f'  partially exercised:      {len(partial)} segments, '
          f'{sum(row["size"] - row["executed"] for row in partial):,} unseen bytes')
    print(f'  dark:                     {len(dark)} segments, '
          f'{sum(row["size"] for row in dark):,} bytes')


if __name__ == '__main__':
    main()
