#ifndef FA18_GLUE_MENU_TRANSITION_H
#define FA18_GLUE_MENU_TRANSITION_H
#include <stdint.h>
#define MENU_TRANSITION_ENTRY(e) int glue_##e(void); int glue_##e##_step(void); int glue_##e##_owns(uint32_t pc);
MENU_TRANSITION_ENTRY(C0FCB4)
MENU_TRANSITION_ENTRY(C0FECE)
MENU_TRANSITION_ENTRY(C0FFE2)
MENU_TRANSITION_ENTRY(C1000A)
MENU_TRANSITION_ENTRY(C17C2A)
MENU_TRANSITION_ENTRY(C24E8A)
#undef MENU_TRANSITION_ENTRY
#endif
