#ifndef FA18_GLUE_MENU_CONTEXT_FINISH_H
#define FA18_GLUE_MENU_CONTEXT_FINISH_H
#include <stdint.h>
#define MENU_CONTEXT_DECLARE(entry) int glue_##entry(void); int glue_##entry##_step(void); int glue_##entry##_owns(uint32_t pc)
MENU_CONTEXT_DECLARE(C10A24); MENU_CONTEXT_DECLARE(C10C08); MENU_CONTEXT_DECLARE(C10C68);
MENU_CONTEXT_DECLARE(C10AB2); MENU_CONTEXT_DECLARE(C10AE6); MENU_CONTEXT_DECLARE(C10B1E);
MENU_CONTEXT_DECLARE(C10CFE); MENU_CONTEXT_DECLARE(C10D8A); MENU_CONTEXT_DECLARE(C10DAE);
MENU_CONTEXT_DECLARE(C11A26); MENU_CONTEXT_DECLARE(C11A50); MENU_CONTEXT_DECLARE(C09192);
MENU_CONTEXT_DECLARE(C16D04); MENU_CONTEXT_DECLARE(C25070);
#undef MENU_CONTEXT_DECLARE
#endif
