#ifndef FA18_GLUE_MENU_RETURN_H
#define FA18_GLUE_MENU_RETURN_H
#include <stdint.h>
#define MENU_RETURN_DECLARE(entry) int glue_##entry(void); int glue_##entry##_step(void); int glue_##entry##_owns(uint32_t pc)
MENU_RETURN_DECLARE(C1064C); MENU_RETURN_DECLARE(C108FE); MENU_RETURN_DECLARE(C10900); MENU_RETURN_DECLARE(C10970);
MENU_RETURN_DECLARE(C102D8); MENU_RETURN_DECLARE(C0FB70); MENU_RETURN_DECLARE(C0FBB6); MENU_RETURN_DECLARE(C101FC);
MENU_RETURN_DECLARE(C10228); MENU_RETURN_DECLARE(C10942); MENU_RETURN_DECLARE(C109AC); MENU_RETURN_DECLARE(C10302);
MENU_RETURN_DECLARE(C10BAE); MENU_RETURN_DECLARE(C10362);
#undef MENU_RETURN_DECLARE
#endif
