#ifndef FA18_GLUE_RECORD_CONTROL_ACTIONS_H
#define FA18_GLUE_RECORD_CONTROL_ACTIONS_H
#include "glue.h"
#define RECORD_ACTION_OWNER(e) int glue_##e(void); int glue_##e##_step(void); int glue_##e##_owns(uint32_t pc);
RECORD_ACTION_OWNER(C153FC)
RECORD_ACTION_OWNER(C15688)
RECORD_ACTION_OWNER(C159AE)
RECORD_ACTION_OWNER(C15AD4)
RECORD_ACTION_OWNER(C181A0)
RECORD_ACTION_OWNER(C15138)
#undef RECORD_ACTION_OWNER
#endif
