#ifndef FA18_GLUE_MENU_OUTCOME_H
#define FA18_GLUE_MENU_OUTCOME_H
#include <stdint.h>
#define MENU_OUTCOME_DECLARE(entry) int glue_##entry(void); int glue_##entry##_step(void); int glue_##entry##_owns(uint32_t pc)
MENU_OUTCOME_DECLARE(C104C2); MENU_OUTCOME_DECLARE(C105F4); MENU_OUTCOME_DECLARE(C1072E); MENU_OUTCOME_DECLARE(C1078A);
MENU_OUTCOME_DECLARE(C105A6); MENU_OUTCOME_DECLARE(C10626); MENU_OUTCOME_DECLARE(C1075A); MENU_OUTCOME_DECLARE(C108DA);
MENU_OUTCOME_DECLARE(C29368);
#undef MENU_OUTCOME_DECLARE
#endif
