#ifndef FA18_GLUE_MENU_COLD_H
#define FA18_GLUE_MENU_COLD_H
#include <stdint.h>
#define MENU_COLD_DECLARE(entry) int glue_##entry(void); int glue_##entry##_step(void); int glue_##entry##_owns(uint32_t pc)
MENU_COLD_DECLARE(C0FE36); MENU_COLD_DECLARE(C1017E); MENU_COLD_DECLARE(C10272);
MENU_COLD_DECLARE(C103E4); MENU_COLD_DECLARE(C09120); MENU_COLD_DECLARE(C09148);
MENU_COLD_DECLARE(C29490); MENU_COLD_DECLARE(C2949A); MENU_COLD_DECLARE(C10B90);
MENU_COLD_DECLARE(C16406);
#undef MENU_COLD_DECLARE
#endif
