"""Stage D porting inventory.

Joins the translator's call graph (port/recomp/generated/recomp_graph.json)
with what earlier work already produced:

- port/game/*.c modules, via the original addresses their headers cite;
- analysis/routines/*.md reports, via the address in the file name;
- the recreated-routine registry (port/game/glue/ports.c) for what is done;
- an optional call profile from `fa18_recomp --profile`.

Writes analysis/port_inventory.md, the porting order (leaves first, then
routines whose callees are all ported), and prints a summary.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ADDR = re.compile(r"\$C([0-9A-Fa-f]{5})(?:-\$C([0-9A-Fa-f]{5}))?")


def load_graph() -> list[dict]:
    return json.loads((ROOT / "port/recomp/generated/recomp_graph.json").read_text())


def routine_of(graph: list[dict]):
    spans = []
    for f in graph:
        for a, b in f["spans"]:
            spans.append((int(a, 16), int(b, 16), f["entry"]))

    def lookup(addr: int) -> str | None:
        best = None
        for a, b, entry in spans:
            if a <= addr < b:
                # Prefer the routine whose entry is closest below the address.
                if best is None or int(entry, 16) > int(best, 16) and int(entry, 16) <= addr:
                    best = entry
        return best
    return lookup


def module_addresses() -> dict[str, list[tuple[int, int | None]]]:
    out = {}
    for h in sorted((ROOT / "port/game").glob("*.h")):
        if h.stem.startswith("run0") or h.stem.endswith("_data"):
            continue
        found = []
        for m in ADDR.finditer(h.read_text(errors="replace")):
            start = int("C" + m.group(1), 16)
            end = int("C" + m.group(2), 16) if m.group(2) else None
            found.append((start, end))
        if found:
            out[h.stem] = found
    return out


def reports() -> dict[str, str]:
    out = {}
    for p in (ROOT / "analysis/routines").glob("c*.md"):
        m = re.match(r"(c[0-9a-f]{5})_", p.name)
        if m:
            out.setdefault(m.group(1).upper(), p.name)
    return out


def ported() -> set[str]:
    path = ROOT / "port/game/glue/ports.c"
    if not path.is_file():
        return set()
    return {m.group(1).upper() for m in re.finditer(r"\{\s*0x([0-9A-Fa-f]{6})", path.read_text())}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--profile", type=Path, help="fa18_recomp --profile JSON (calls per routine)")
    parser.add_argument("--out", type=Path, default=ROOT / "analysis/port_inventory.md")
    args = parser.parse_args()

    graph = load_graph()
    by_entry = {f["entry"]: f for f in graph}
    lookup = routine_of(graph)
    calls = json.loads(args.profile.read_text()) if args.profile else {}
    done = ported()
    reps = reports()

    modules_for: dict[str, list[str]] = {}
    unmatched = []
    for module, addrs in module_addresses().items():
        hits = {lookup(a) for a, _ in addrs} - {None}
        if not hits:
            unmatched.append(module)
        for entry in hits:
            modules_for.setdefault(entry, []).append(module)

    callers: dict[str, set[str]] = {}
    for f in graph:
        for c in f["calls"]:
            callers.setdefault(c, set()).add(f["entry"])

    def clean(f):
        k = f["kinds"]
        return not f["dynamic_calls"] and not f["jumps_out"] and "interp" not in k and "undecodable" not in k

    # Porting waves: a routine is ready when all its static callees are ported
    # (or in an earlier wave) and it has no dynamic calls or jumps out.
    wave = {}
    remaining = {f["entry"] for f in graph if clean(f)}
    level = 0
    settled = set(done)
    while remaining:
        ready = {e for e in remaining if all(c in settled or c in wave for c in by_entry[e]["calls"])}
        if not ready:
            break
        for e in ready:
            wave[e] = level
        settled |= ready
        remaining -= ready
        level += 1

    rows = []
    for f in graph:
        e = f["entry"]
        rows.append({
            "entry": e, "insns": f["instructions"], "calls": len(f["calls"]),
            "callers": len(callers.get(e, ())), "wave": wave.get(e),
            "profile": calls.get(e, 0), "modules": modules_for.get(e, []),
            "report": reps.get(e), "ported": e in done, "clean": clean(f)})
    rows.sort(key=lambda r: (r["wave"] is None, r["wave"] if r["wave"] is not None else 99,
                             -r["profile"], r["entry"]))

    lines = ["# Stage D porting inventory", "",
             "Generated by `tools/recomp/inventory.py`; do not edit. Wave 0 routines call",
             "nothing; wave N calls only routines in earlier waves. `modules` are existing",
             "`port/game/` modules whose cited addresses fall inside the routine.", "",
             f"- routines: {len(rows)}; ported: {sum(r['ported'] for r in rows)}; "
             f"in waves: {len(wave)}; with an existing module: "
             f"{sum(1 for r in rows if r['modules'])}; with a report: {sum(1 for r in rows if r['report'])}",
             f"- modules not inside any translated routine: {len(unmatched)}", "",
             "| routine | wave | insns | calls | callers | profile calls | ported | modules | report |",
             "| --- | ---: | ---: | ---: | ---: | ---: | --- | --- | --- |"]
    for r in rows:
        lines.append(f"| `${r['entry']}` | {'' if r['wave'] is None else r['wave']} | {r['insns']} | "
                     f"{r['calls']} | {r['callers']} | {r['profile']} | {'yes' if r['ported'] else ''} | "
                     f"{', '.join(r['modules'])} | {r['report'] or ''} |")
    lines += ["", "## Modules not inside any translated routine", ""]
    lines += [f"- `{m}`" for m in unmatched]
    args.out.write_text("\n".join(lines) + "\n")
    print(json.dumps({"routines": len(rows), "waves": level, "in_waves": len(wave),
                      "wave0": sum(1 for v in wave.values() if v == 0),
                      "with_module": sum(1 for r in rows if r["modules"]),
                      "with_report": sum(1 for r in rows if r["report"]),
                      "unmatched_modules": len(unmatched), "ported": len(done)}))


if __name__ == "__main__":
    main()
