/* Validation mappings from the existing original-instruction component oracles. */
#define DISPATCH_B_FIELDS(X) \
 X(c.indexed.mode,MODE_SELECT) \
 X(c.indexed.mode_request,0xc45792u) \
 X(c.indexed.mode_gate,COMMAND_MODE_GATE) \
 X(c.indexed.enable_gate,COMMAND_ENABLE_GATE) \
 X(c.indexed.enable_selection,0xc45849u) \
 X(c.indexed.function_modifier,KEY_STATE+1) \
 X(c.indexed.recorder_mode,RECORDER_MODE) \
 X(c.indexed.cockpit_high_byte,COCKPIT_FLAGS) \
 X(c.indexed.pose_entry,SCENE_POSE_ENTRY) \
 X(c.indexed.pose_inhibit,CONTEXT_GATE) \
 X(c.indexed.origin_detail,ORIGIN_DETAIL_MODE) \
 X(c.indexed.origin_gate_a,ORIGIN_GATE_A) \
 X(c.indexed.origin_gate_b,ORIGIN_GATE_B) \
 X(c.indexed.function_level,FUNCTION_KEY_LEVEL) \
 X(c.indexed.control_record_level,CONTROL_RECORDS+0x2bu) \
 X(c.indexed.player_ready,PLAYER_READY) \
 X(c.event_counter,COMMAND_EVENT_COUNTER) \
 X(c.origin_mode,ORIGIN_ENABLE) \
 X(c.modifier,KEY_STATE) \
 X(c.other_modifier,KEY_STATE+2) \
 X(c.return_state,COMMAND_RETURN_STATE) \
 X(c.block_flags,COMMAND_BLOCK_FLAGS) \
 X(c.message_state,MESSAGE_STATE_C) \
 X(f.redraw_e,BAR_REDRAWS_E) \
 X(f.redraw_b,BAR_REDRAWS_B) \
 X(f.redraw_c,BAR_REDRAWS_C) \
 X(f.redraw_d,BAR_REDRAWS_D) \
 X(f.scale_redraws,SCALE_REDRAWS) \
 X(f.info_request,INFO_REQUEST) \
 X(f.info_redraws,INFO_REDRAWS) \
 X(f.hud_mode,POST_INPUT_EXPIRED) \
 X(f.trim_input,COMMAND_TRIM_INPUT) \
 X(f.next_target,COMMAND_NEXT_TARGET_FLAG) \
 X(f.script_count,SCRIPT_COUNT) \
 X(f.weapon_pause,COMMAND_WEAPON_PAUSE) \
 X(f.weapon_mode_redraws,COMMAND_WEAPON_MODE_REDRAWS) \
 X(f.weapon_redraws,WEAPON_REDRAWS) \
 X(f.shoot_cue,SHOOT_CUE) \
 X(f.gear_message,COMMAND_GEAR_MESSAGE) \
 X(f.flare_count,MISSION_LEVEL_B) \
 X(f.chaff_count,MISSION_LEVEL_A) \
 X(f.flare_timer,COMMAND_FLARE_TIMER) \
 X(f.chaff_timer,COMMAND_CHAFF_TIMER) \
 X(f.mission_flags,MISSION_FLAGS_A) \
 X(f.ecm_enabled,PLAYER_FLAGS_G) \
 X(f.sequence_phase,SEQUENCE_PHASE) \
 X(f.eject_flag,BAR_E_FLAG) \
 X(f.pause,PAUSE_A) \
 X(f.context_started,CONTEXT_STARTED) \
 X(f.stick_y,STICK_Y) \
 X(f.stick_x,STICK_X) \
 X(v.detail_index,ORIGIN_DETAIL_INDEX) \
 X(v.update_mask,UPDATE_MASK) \
 X(v.fire_state,FIRE_STATE) \
 X(v.mode,VIEW_MODE) \
 X(v.mode_auxiliary,0xc457a8u) \
 X(v.mode_companion,0xc457a9u) \
 X(v.refresh_request,0xc45891u) \
 X(v.zoom_flags,ZOOM_FLAGS) \
 X(v.redraw_first,REDRAW_FIRST) \
 X(v.gauge_refresh,GAUGE_REFRESH) \
 X(v.grid_z_redraws,GRID_Z_REDRAWS) \
 X(v.grid_x_redraws,GRID_X_REDRAWS) \
 X(v.redraw_bar_a,BAR_REDRAWS_A) \
 X(v.redraw_bar_aux,0xc45841u) \
 X(v.display_update,DISPLAY_UPDATE) \
 X(v.redraw_keep_state,REDRAW_KEEP_STATE) \
 X(context.view_request,0xc45833u) \
 X(context.track_started,TRACK_STARTED) \
 X(context.recorder_on,RECORDER_ON) \
 X(c.indexed.modes.level,rd_u32(MODE_TABLE)+6)
#define DISPATCH_W_FIELDS(X) \
 X(f.emitted_requests,PENDING_COMMAND_WORD_A) \
 X(f.command_word,COMMAND_WORD) \
 X(f.info_page,INFO_PAGE) \
 X(f.spawn_gate,COMMAND_SPAWN_GATE) \
 X(v.target_mark,TARGET_MARK) \
 X(v.span_origin,SPAN_ORIGIN) \
 X(v.span_origin_y,SPAN_ORIGIN_Y) \
 X(v.line_last_row,LINE_LAST_ROW) \
 X(v.zoom_scale,ZOOM_SCALE) \
 X(v.redraw_state_word,REDRAW_STATE_WORD) \
 X(v.emitted_requests,PENDING_COMMAND_WORD_B) \
 X(context.angle_history,ORIGIN_ANGLE_HISTORY) \
 X(context.pan,VIEW_PAN) \
 X(context.rotate,VIEW_ROTATE) \
 X(c.pending_a,RECORD_WORD_A) \
 X(c.pending_b,RECORD_WORD_B) \
 X(c.indexed.throttle,CONTROL_ACCUMULATOR_Y) \
 X(c.indexed.throttle_companion,CONTROL_ACCUMULATOR_COMPANION) \
 X(c.indexed.modes.status,rd_u32(MODE_TABLE)) \
 X(dispatch.error_code,ERROR_CODE)
#define DISPATCH_L_FIELDS(X) \
 X(v.origin_middle,SELECTOR_ORIGIN_MIDDLE) \
 X(v.redraw_state_long,REDRAW_STATE_LONG) \
 X(context.origin_first,SELECTOR_ORIGIN) \
 X(context.origin_third,SELECTOR_ORIGIN_THIRD) \
 X(context.map_middle_cache,0xc45664u) \
 X(context.negated[0],ORIGIN_NEGATED_COMPANION) \
 X(context.negated[1],ORIGIN_NEGATED_COMPANION+4) \
 X(context.negated[2],ORIGIN_NEGATED_COMPANION+8) \
 X(context.smoothed_delta,ORIGIN_SMOOTHED_DELTA) \
 X(context.auxiliary_delta[0],ORIGIN_AUXILIARY_DELTA) \
 X(context.auxiliary_delta[1],ORIGIN_AUXILIARY_DELTA+4) \
 X(c.indexed.playback_bytes,PLAYBACK_BYTES) \
 X(f.gear_gate,COMMAND_GEAR_GATE)
