"""Bind deferred translations to native instruction helpers; track decompilation debt.

This partitions the existing byte-backed translation without changing function
IDs, labels, spans, liveness or instruction order. Run after recomp.py, or run
standalone against the checked-in translation. --check verifies reproducibility.
The original opcode helper definitions are copied exactly from m68kops.c;
the shared CPU state, bus and chipset timeline remain in use.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from native_call_graph import native_entries

ROOT = Path(__file__).resolve().parents[2]
GEN = ROOT / "port/recomp/generated"
STATIC_FILE = "recomp_static_deferred.c"
MARKER = "STATIC_RECOMP"
FUNCTION = re.compile(r"int fa18_fn_([0-9A-F]{6})\(int entry\) \{.*?\n\}", re.S)
OPCODE = re.compile(r"FA18_\w+\(0x[0-9A-F]{6}, (0x[0-9A-F]{4})")
HEADER = ('/* Generated by tools/recomp/recomp.py. Do not edit. */\n'
          '#define FA18_RECOMP_GENERATED\n#include "recomp_runtime.h"\n\n'
          '#include "recomp_functions.h"\n\n')


def digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def instruction_helpers(source: str, opcodes: set[str]) -> dict[str, str]:
    """Apply the original ordered mask table: later matches override earlier ones."""
    table = source[source.index("m68k_opcode_handler_table[]"):]
    rows = [(name, int(mask, 16), int(match, 16)) for name, mask, match in
            re.findall(r"\{(m68k_op_\w+)\s*,\s*(0x[0-9a-f]+),\s*(0x[0-9a-f]+)", table)]
    if not rows:
        raise ValueError("cannot read Musashi opcode table")
    result = {}
    for opcode in sorted(opcodes):
        matches = [name for name, mask, match in rows if int(opcode, 16) & mask == match]
        if not matches or matches[-1] == "m68k_op_illegal":
            raise ValueError(f"no valid static helper for {opcode}")
        result[opcode] = matches[-1]
    return result


def helper_body(source: str, name: str) -> str:
    matches = re.findall(r"^static (?:int|void) " + re.escape(name) +
                         r"\([^\n]*\)\n\{.*?\n\}", source, re.M | re.S)
    if len(matches) != 1:
        raise ValueError(f"expected one original helper body for {name}")
    return matches[0]


def outputs(directory: Path = GEN) -> dict[Path, str]:
    graph = json.loads((directory / "recomp_graph.json").read_text())
    registered = set(re.findall(r"^\s*\{0x([0-9A-F]{6}),", (ROOT / "port/game/glue/ports.c").read_text(), re.M))
    native = native_entries(graph, registered)
    expected = {row["entry"] for row in graph}
    pending = expected - registered - native.keys()
    bodies = {}
    normal_paths = sorted(directory.glob("recomp_[0-9]*.c"))
    source_paths = normal_paths + ([directory / STATIC_FILE] if (directory / STATIC_FILE).exists() else [])
    for path in source_paths:
        for match in FUNCTION.finditer(path.read_text()):
            entry = match[1]
            if entry in bodies:
                raise ValueError(f"duplicate generated entry {entry}")
            bodies[entry] = match[0]
    if bodies.keys() != expected:
        raise ValueError(f"translation inventory differs: missing {sorted(expected - bodies.keys())}, "
                         f"extra {sorted(bodies.keys() - expected)}")

    core = (ROOT / "tools/musashi/m68kops.c").read_text()
    opcodes = set(OPCODE.findall("\n".join(bodies[e] for e in sorted(pending))))
    helpers = instruction_helpers(core, opcodes)
    names = sorted(set(helpers.values()))
    operations = [helper_body(core, name) for name in names]
    dependencies = sorted(set(re.findall(r"\b(fa18_\w+)\(", "\n".join(operations))))
    support = [helper_body(core, name) for name in dependencies]
    static = [
        '/* Generated by tools/recomp/static_recomp.py. Do not edit.\n'
        ' * STATIC_RECOMP: original instruction/control-flow translation.\n'
        ' * TODO(decompile): replace each marked entry with readable domain C.\n'
        ' * Instruction helpers are copied from tools/musashi/m68kops.c.\n'
        ' * Shared CPU state, memory, exception and bus timing remain required. */',
        '#define FA18_RECOMP_GENERATED', '#include "recomp_runtime.h"',
        '#include "recomp_functions.h"', '',
        *support, *operations, '',
        '/* Bind each constant opcode to its native helper at compile time. */',
        *[f"#define FA18_STATIC_{opcode} {name}" for opcode, name in helpers.items()],
        '#define FA18_STATIC_HELPER_(op) FA18_STATIC_##op',
        '#define FA18_STATIC_HELPER(op) FA18_STATIC_HELPER_(op)',
        '#ifndef FA18_STATIC_RECOMP_REFERENCE',
        '#undef FA18_EXEC',
        '#define FA18_EXEC(pc, op) FA18_EXEC_USING(pc, op, FA18_STATIC_HELPER(op)())',
        '#endif', '',
    ]
    layout = json.loads((ROOT / "analysis/data/romfree_hunk_layout.json").read_text())
    code = [segment for segment in layout["segments"] if segment["kind"] == "CODE"]
    rows = []
    for row in graph:
        entry = row["entry"]
        if entry not in pending:
            continue
        static.extend([f"/* STATIC_RECOMP: ${entry}. TODO(decompile): complete readable owner;",
                       ' * retain shared tails, original child returns and CPU/RAM effects. */',
                       bodies[entry], ''])
        address = int(entry, 16)
        segments = [s["index"] for s in code if s["payload_base"] <= address <
                    s["payload_base"] + s["payload_size"]]
        rows.append({
            "entry": entry, "status": "static_recompiled_deferred_decompilation",
            "source": "port/recomp/generated/" + STATIC_FILE,
            "original_code_hunks": segments,
            "origin": "original_adf_code" if segments else "reference_runtime_wrapper",
            "instructions": row["instructions"], "spans": row["spans"],
            "calls": row["calls"], "dynamic_calls": row["dynamic_calls"],
            "jumps_out": row["jumps_out"], "translation_sha256": digest(bodies[entry]),
            "follow_up": "Prove complete callable owner and replace with readable domain C.",
        })

    result = {directory / STATIC_FILE: "\n".join(static).rstrip() + "\n"}
    # Keep regular translation buckets stable, including empty buckets, so the
    # full generator and standalone partition have identical results.
    chunk_size = json.loads((directory / "recomp_manifest.json").read_text()).get("functions_per_file", 150)
    ordered = sorted(expected)
    for start in range(0, len(ordered), chunk_size):
        chunk = ordered[start:start + chunk_size]
        result[directory / f"recomp_{start // chunk_size:03d}.c"] = HEADER + "\n\n".join(
            bodies[e] for e in chunk if e not in pending) + "\n"
    inventory = {
        "schema": 1, "translated_entries": len(graph),
        "registered_readable_translated_entries": len(expected & registered),
        "registered_readable_source_only_entries": len(registered - expected),
        "direct_native_entries": list(native.values()),
        "direct_native_entry_count": len(native),
        "static_recompiled_entries": len(pending),
        "original_adf_static_entries": sum(bool(row["original_code_hunks"]) for row in rows),
        "reference_wrapper_static_entries": sum(not row["original_code_hunks"] for row in rows),
        "readable_decompilation_complete": not pending,
        "whole_original_call_graph_complete": False,
        "cpu_and_chipset_required": True,
        "instruction_helper_authority": "tools/musashi/m68kops.c",
        "instruction_helpers_sha256": digest("\n".join(support + operations)),
        "opcodes": helpers, "entries": rows,
    }
    result[directory / "recomp_deferred.json"] = json.dumps(inventory, indent=2) + "\n"
    return result


def partition(directory: Path = GEN, check: bool = False) -> None:
    generated = outputs(directory)
    changed = [path for path, text in generated.items() if not path.exists() or path.read_text() != text]
    if check and changed:
        raise ValueError("stale static recompilation: " + ", ".join(str(p.relative_to(ROOT)) for p in changed))
    if not check:
        for path in changed:
            path.write_text(generated[path], newline="\n")
    inventory = json.loads(generated[directory / "recomp_deferred.json"])
    print(f"static recompilation: {inventory['static_recompiled_entries']} deferred entries, "
          f"{inventory['registered_readable_translated_entries']} readable translated, "
          f"{inventory['registered_readable_source_only_entries']} readable source-only; "
          f"{inventory['direct_native_entry_count']} direct C entries without CPU entry adapters; "
          f"{len(inventory['opcodes'])} direct opcode bindings")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    partition(check=args.check)


if __name__ == "__main__":
    main()
